app/models/users.py
from .db import get_connection
from werkzeug.security import generate_password_hash, check_password_hash

mydb = get_connection()

class User:

    def __init__(self, 
                 username, 
                 password,
                 email,
                 first_name = '',
                 last_name = '',
                 image = '',
                 id = None):
        self.id = id
        self.username = username
        self.password = password
        self.email = email
        self.first_name = first_name
        self.last_name = last_name
        self.image = image

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
                self.password = generate_password_hash(self.password)
                sql = "INSERT INTO users(username, password, email) VALUES(%s, %s, %s)"
                val = (self.username, self.password, self.email)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        else:
            with mydb.cursor() as cursor:
                sql = 'UPDATE users SET first_name = %s, last_name = %s, email = %s, image = %s '
                sql += 'WHERE id = %s'
                val = (self.first_name, self.last_name, self.email, self.image, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM users WHERE id = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id

    @staticmethod
    def __get__(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM users WHERE id = { id }"
            cursor.execute(sql)

            user = cursor.fetchone()

            if user:
                user = User(username=user["username"], #username
                            password=user["password"], #password
                            first_name=user["first_name"], #first_name
                            last_name=user["last_name"], #last_name
                            email=user["email"], #email
                            image=user["image"], #image
                            id=id)
                return user
            
            return None
    
    @staticmethod
    def check_email(email):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM users WHERE email = '{ email }'"
            cursor.execute(sql)

            user = cursor.fetchone()

            if user:
                return 'User exist'
            else:
                return None
    
    @staticmethod
    def check_username(username):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM users WHERE username = '{ username }'"
            cursor.execute(sql)

            user = cursor.fetchone()

            if user:
                return 'User exist'
            else:
                return None
            
    @staticmethod
    def get_by_password(username, password):
        with mydb.cursor(dictionary=True) as cursor:
            sql = "SELECT id, username, password FROM users WHERE username = %s"
            val = (username,)
            cursor.execute(sql, val)
            user = cursor.fetchone()
            
            if user != None:
                if check_password_hash(user["password"], password):
                    return User.__get__(user["id"])
            return None

    @staticmethod
    def get_all():
        users = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM users"
            cursor.execute(sql)
            result = cursor.fetchall()
            for user in result:
                users.append(
                    User(username=user["username"],
                         password=user["password"],
                         email=user["email"],
                         first_name=user["first_name"],
                         last_name=user["last_name"],
                         id=user["id"])
                )
            return users

    def __str__(self):
        return f"{ self.username } { self.first_name } { self.last_name }"

app/forms/user_forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, PasswordField, EmailField, 
                     SubmitField, ValidationError)
from wtforms.validators import DataRequired, Email, EqualTo, Length
from flask_wtf.file import FileField, FileAllowed

from models.users import User

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(),
                                                    EqualTo('password_confirm', 
                                                            message='Las contraseñas deben coincidir')])
    password_confirm = PasswordField('Password Confirm', validators=[DataRequired()])
    submit = SubmitField('Registrar')

    ######## Validar Correo Unico #########
    def validate_email(self, field):
        ######## Consultar si el correo existe en la base de datos #######
        if User.check_email(field.data):
            raise ValidationError('El correo ya existe')

    ######## Validar Username Unico #########
    def validate_username(self, field):
        ######## Consultar si el username existe en la base de datos #######
        if User.check_username(field.data):
            raise ValidationError('El username ya existe')
        
        
################# Formulario de Login ##################
class LoginForm(FlaskForm):
    username = StringField('Usuario', validators=[DataRequired()])
    password = PasswordField('Contraseña', validators=[DataRequired()])
    submit = SubmitField('Ingresar')

################ Formulario de Perfil ################
class ProfileForm(FlaskForm):
    # username No se edita
    # password No se edita
    # email, Verificar antes de actualizar
    first_name = StringField('Nombre',
                             validators=[DataRequired(), Length(min=3, max=30)])
    last_name = StringField('Apellidos', 
                            validators=[DataRequired(), Length(min=10, max=40)])
    image = FileField('Imagen de Perfil', 
                      validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'Solo imagenes!')])
    submit = SubmitField('Actualizar')
    
class UpdateUserForm(FlaskForm):
    first_name = StringField('Nombre', validators=[DataRequired('Este campo es obligatorio')])
    last_name = StringField('Apellido', validators=[DataRequired('Este campo es obligatorio')])
    email = EmailField('Email', validators=[DataRequired(), Email('Usa una dirección de correo válida')])
    username = StringField('Usuario', validators=[DataRequired('Este campo es obligatorio')])

app/views/product_views.py
from flask import Blueprint, render_template, redirect, url_for, abort, session, request, flash

from models.products import Product 

from forms.product_forms import UpdateProductForm, CreateProductForm

from models.categories import Category

from utils.file_handler import save_image

product_views = Blueprint('product', __name__)

@product_views.route('/products/')
@product_views.route('/products/<int:page>/')
def home(page=1):
    if "user" in session:
        limit = 10
        products = Product.get_all(limit=limit, page=page)
        total_products = Product.count()
        pages = total_products // limit
        user = session.get("user")
        return render_template('products/product.html', products=products, pages=pages, user=user)
    return redirect(url_for('user.login'))

@product_views.route('/products/<int:page>/')
def next(page=2):
    if "user" in session:
        limit = 10
        products = Product.get_all(limit=limit, page=page)
        total_products = Product.count()
        pages = total_products // limit
        user = session.get("user")
        return render_template('products/product.html', products=products, pages=pages, user=user)
    return redirect(url_for('user.login'))

@product_views.route('/products/create/', methods=('GET', 'POST'))
def create():
    if "user" in session:#Linea de sesion
        form = CreateProductForm()
        if form.validate_on_submit():
            name = form.name.data
            price = form.price.data
            stock = form.stock.data
            size = form.size.data
            category_id = form.category_id.data
            f = form.image.data
            image=""
            if f:
                image = save_image(f, 'images/products')
            product = Product(name=name,
                            price=price,
                            stock=stock,
                            size=size,
                            category_id=category_id,
                            image=image)
            print(product)
            product.save()
            return redirect(url_for('product.home'))
        return render_template('products/create_prod.html', form=form)
    return redirect(url_for('user.login'))#LINEA DE SESION 

@product_views.route('/products/<int:id>/update/', methods=('GET', 'POST'))
def update_prod(id):
    if "user" in session:
        form = UpdateProductForm()
        categories = Category.get_all()
        cats = [(-1, '')]
        for cat in categories:
            cats.append((cat.id, cat.category))
        form.category_id.choices = cats
        product = Product.get(id)
        if product is None:
            abort(404)
        if form.validate_on_submit():
            product.name = form.name.data
            product.size = form.size.data
            product.price = form.price.data
            product.stock = form.stock.data
            product.category_id = form.category_id.data
            f = form.image.data
            if f:
                image = save_image(f, 'images/products')
                product.image = image
            product.save()
            return redirect(url_for('product.home'))
        form.name.data = product.name
        form.size.data = product.size
        form.price.data = product.price
        form.stock.data = product.stock
        form.category_id.data = product.category_id
        image = product.image
        return render_template('products/create_prod.html', form=form, image=image)
    return redirect(url_for('user.login'))


@product_views.route('/products/<int:id>/detail/')
def detail(id):
    if "user" in session:
        product = Product.get(id)
        if product is None: abort(404)
        cat = Category.get(product.category_id)
        return render_template('products/details.html', product=product, cat=cat)
    return redirect(url_for('user.login'))

@product_views.route('/product/<int:id>/delete/', methods=['POST'])
def delete(id):
    if "user" in session:
        product = Product.get(id)
        if product is None: abort(404)
        product.delete()
        return redirect(url_for('product.home'))
    return redirect(url_for('user.login'))

@product_views.route('/products/buscar/', methods=['GET','POST'])
def search():
    result = None
    if request.method == "POST":
        result = Product.search(result)
        search  = request.form['buscar']
        return render_template('products/busqueda.html', miData = result, busqueda = search)
    return redirect(url_for('product.home')) 

@product_views.before_request
def antes_de_iniciar():
    ruta = request.path
    if 'user' not in session and ruta != "/products/" and ruta != "/products/create/" and not ruta.startswith("/static"):
        flash("Es necesario iniciar sesion.")
        return redirect(url_for('user.login'))

app/views/user_views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, session, request

from models.users import User

from forms.user_forms import RegisterForm, LoginForm, ProfileForm

from utils.file_handler import save_image

user_views = Blueprint('user', __name__)

@user_views.route('/users/')
@user_views.route('/users/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.get_by_password(username, password)
        if not user:
            flash('Verifica tus Datos')
        else:
            session["user"]= user.username
            return redirect(url_for('home.home'))
    return render_template('users/login.html', form=form)


@user_views.route('/users/<int:page>/', methods=('GET',))
def users(page=1):
    if "user" in session:
        limit = 10
        users = User.get_all(limit=limit, page=page)
        total_users = User.count()
        pages = total_users // limit
        user = session.get("user")
        return render_template('users/users.html', users=users, pages=pages, user=user)
    return redirect(url_for('user.login'))

@user_views.route('/users/register/', methods=('GET', 'POST'))
def register():
    if "user" in session:
        form = RegisterForm()

        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            email = form.email.data

            user = User(username, password, email)
            user.save()
            flash('Usario registrado con exito!')
            return redirect(url_for('user.logout'))
        return render_template('users/register.html', form=form)
    return redirect(url_for('user.login'))

@user_views.route('/users/logout/')
def logout():
    session.pop('user',None)
    return redirect(url_for('user.login'))

@user_views.route('/users/T&C Bar - Restaurante "El Toro Bravo: Food and Drinks"/')
def conditions():
    return render_template('home/conditions.html')


@user_views.route('/users/<int:id>/profile/', methods=('GET', 'POST'))
def profile(id):
    if "user" in session:
        form = ProfileForm()
        user = User.__get__(id)
        if not user:
            abort(404)
        if form.validate_on_submit():
            user.first_name = form.first_name.data
            user.last_name = form.last_name.data
            f = form.image.data
            if f:
                user.image = save_image(f, 'images/profiles', user.username)
            user.save()
        form.first_name.data = user.first_name
        form.last_name.data = user.last_name
        image = user.image
        return render_template('users/profile.html', form=form, image=image)
    return redirect(url_for('user.login'))

@user_views.before_request
def antes_de_iniciar():
    ruta = request.path
    if 'user' not in session and ruta != "/users/" and ruta != "/users/logout/" and not ruta.startswith("/static") and ruta != "/users/login/":
        flash("Es necesario iniciar sesion.")
        return redirect(url_for('user.login'))
    

app/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock title %}
    
{% block content %}
<h1>Iniciar Sesión</h1>
{% for message in get_flashed_messages() %}
<p>{{ message }}</p>
{% endfor %}
<form method="post">
    {% with message = get_flashed_messages  %}

    {% if message %}
    <br/>
    {% for message in messages %}
    <div class="alert alert-primary alert-dismissible" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-class" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>   
    {% endfor %}
        
    {% endif %} 
    {% endwith %}
    {{ form.csrf_token }}
    <div>
        {{ form.username.label }}
        {{ form.username() }}
        {% if form.username.errors %}
            {% for error in form.username.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.password.label }}
        {{ form.password() }}
        {% if form.password.errors %}
            {% for error in form.password.errors %}
            <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.submit(class="btn") }}
    </div>
</form>
{% endblock %}
    

app/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
Profile
{% endblock %}

{% block content %}
<div>
    {% if image %}
        <img src="{{ url_for('static', filename='images/profiles/' + image) }}" 
            alt="Imagen de Perfil de Usuario"
            width="200px">
    {% else %}
        <img src="{{ url_for('static', filename='images/profiles/user-image.png') }}"
            alt="Imagen de Perfil de Usuario"
            width="200px">
    {% endif %}
</div>
<form method="post", enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div>
        {{ form.first_name.label }}
        {{ form.first_name() }}
        {% if form.first_name.errors %}
            {% for error in form.first_name.errors %}
                <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.last_name.label }}
        {{ form.last_name() }}
        {% if form.last_name.errors %}
            {% for error in form.last_name.errors %}
                <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.image.label }}
        {{ form.image() }}
        {% if form.image.errors %}
            {% for error in form.image.errors %}
                <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.submit(class="btn") }}
    </div>
</form>
{% endblock %}
    

app/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<h1>Registrarse</h1>
<form method="post">
    {{ form.csrf_token }}
    <div>
        {{ form.username.label }}
        {{ form.username() }}
        {% if form.username.errors %}
            {% for error in form.username.errors %}
            <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.email.label }}
        {{ form.email() }}
        {% if form.email.errors %}
            {% for error in form.email.errors %}
            <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.password.label }}
        {{ form.password() }}
        {% if form.password.errors %}
            {% for error in form.password.errors %}
            <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.password_confirm.label }}
        {{ form.password_confirm() }}
        {% if form.password_confirm.errors %}
            {% for error in form.password_confirm.errors %}
            <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <br/>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckIndeterminateDisabled"  required>
        <label class="form-check-label" for="flexCheckIndeterminateDisabled">
          Acepto los <a href="{{ url_for('user.conditions') }}">Términos&Condiciones.</a>
        </label>
      </div>
      <br/>
    <div>
        {{ form.submit(class="btn") }}
    </div>
</form>
{% endblock %}
    

app/templates/users/users.html
{% extends 'base.html' %}

{% block title %}
Users
{% endblock %}
    
{% block content %}
<h1>Usuarios</h1>
<a href="{{ url_for('user.register') }}" class="custom-btn">Nuevo Usuario</a>
<nav>
    <div class="search-bar">
      <form name="formSearch" method="POST" action="{{ url_for('product.search') }}" class="search" autocomplete="off">
        <input type="search" name="buscar" class="search__input" placeholder="Busqueda por nombre" required>
        <button type="submit" class="search__btn">
          <i class="bi bi-search search__icon"></i>
          Buscar
        </button>
      </form>
    </div>
  </nav>
<table id="users">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
            <th>Acciones</th> 
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.firs_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <img src="{{ url_for('static', filename='images/users/' + users.image) }}" alt="" width="100px">
                </td>
                <td>
                    <td>
                        <a href="{{ url_for('user.update_user', id=user.id) }}">
                            <i class="fa fa-pencil"></i>
                        </a>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<hr>
{% for i in range(pages) %}
{% endfor %}
{% endblock %}