app/models/categories.py
from .db import get_connection

mydb = get_connection()

class Category:

    def __init__(self, category, description, id=None):
        self.id = id
        self.category = category
        self.description = description

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO categoria_producto(category, description) VALUES(%s, %s)"
                val = (self.category, self.description)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE categoria_producto SET category = %s, description = %s WHERE id = %s"
                val = (self.category, self.description, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM categoria_producto WHERE id = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id
            
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT category, description FROM categoria_producto WHERE id = { id }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            category = Category(result["category"], result["description"], id)
            return category
        
    @staticmethod
    def get_all():
        categories = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT id, category, description FROM categoria_producto"
            cursor.execute(sql)
            result = cursor.fetchall()
            for item in result:
                categories.append(Category(item["category"], item["description"], item["id"]))
            return categories
    
    @staticmethod
    def count_all():
        with mydb.cursor() as cursor:
            sql = f"SELECT COUNT(id) FROM categoria_producto"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result[0]
        
    def __str__(self):
        return f"{ self.id } - { self.category }"

app/forms/category_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class CreateCategoryForm(FlaskForm):
    category = StringField('Categoria', 
                           validators=[DataRequired()])
    description = TextAreaField('Descripcion',
                                validators=[DataRequired()])
    submit = SubmitField('Guardar')
    
class UpdateCategoryForm(FlaskForm):
    category = StringField('Categoria', 
                           validators=[DataRequired()])
    description = TextAreaField('Descripcion',
                                validators=[DataRequired()])
    submit = SubmitField('Guardar')

app/views/category_views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session

from models.categories import Category 

from forms.category_forms import UpdateCategoryForm, CreateCategoryForm

category_views = Blueprint('category', __name__)

@category_views.route('/categories/')
def categories():
    if "user" in session:
        categories = Category.get_all()
        user = session.get("user")
        return render_template('categories/categories.html',
                            categories=categories, user=user)
    return redirect(url_for('user.login'))


@category_views.route('/categories/create/', methods=('GET', 'POST'))
def create_cat():
    if "user" in session:
        form = CreateCategoryForm()
        if form.validate_on_submit():
            category = form.category.data
            description = form.description.data
            cat = Category(category, description)
            cat.save()
            return redirect(url_for('category.categories'))
        return render_template('categories/create_cat.html', form=form)
    return redirect(url_for('user.login'))

@category_views.route('/categories/<int:id>/update/', methods=('GET', 'POST'))
def update_cat(id):
    if "user" in session:
        form = UpdateCategoryForm()
        cat = Category.get(id)
        if form.validate_on_submit():
            cat.category = form.category.data
            cat.description = form.description.data
            cat.save()
            return redirect(url_for('category.categories'))
        form.category.data = cat.category
        form.description.data = cat.description
        return render_template('categories/create_cat.html', form=form )
    return redirect(url_for('user.login'))

@category_views.route('/categories/<int:id>/delete/', methods=('POST',))
def delete_cat(id):
    if "user" in session:
        cat = Category.get(id)
        cat.delete()
        return redirect(url_for('category.categories'))
    return redirect(url_for('user.login'))

@category_views.before_request
def antes_de_iniciar():
    ruta = request.path
    if 'user' not in session and ruta != "/categories/" and ruta != "/categories/create/" and not ruta.startswith("/static"):
        flash("Es necesario iniciar sesion.")
        return redirect(url_for('user.login'))

app/templates/categories/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock %}
    
{% block content %}
<h1>Categorias</h1>
<a href="{{ url_for('category.create_cat') }}" class="btn btn-success">Nueva Categoria</a>
<div class="container">
<table id="categories">
    <thead>
        <tr>
            <th>ID</th>
            <th>Categoria</th>
            <th>Descripción</th>
            <th>Acciones</th>
        </tr>
    </thead>
    
	</div>
    <tbody>
        {% for cat in categories %}
            <tr>
                <td>{{ cat.id }}</td>
                <td>{{ cat.category }}</td>
                <td>{{ cat.description }}</td>
                <td class="action-icons-container">
                    <a href="{{ url_for('category.update_cat', id=cat.id) }}" class="action-icon">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <form action="{{ url_for('category.delete_cat', id=cat.id) }}" method="post">
                        <button type="submit" onclick="return confirm('Seguro?')" class="action-icon">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
    

app/templates/categories/create_cat.html
{% extends 'base.html' %}
{% block title %}
Agregar Categoria 
{% endblock  %}

{% block content %}
<h1>Agregar categoría</h1>
<div class="form-container">
    <form method="post" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div>
            {{form.category.label}}
            {{form.category(placeholder="Categoria")}}
            {% if form.category.errors %}
                {% for error in form.category.errors%}
                <p>{{error}}</p>
                {% endfor %}  
            {% endif %}
        </div>
        <div>
            {{form.description.label}}
            {{form.description()}}
            {% if form.description.errors %}
                {% for error in form.description.errors%}
                <p>{{error}}</p>
                {% endfor %}  
            {% endif %}
        </div>
        <div>
            {{form.submit(class="btn btn-success")}}
        </div>
    </form>
</div>
<a href="{{ url_for('category.categories') }}" class="btn btn-warning">Regresar</a>
{% endblock %}
        