app/models/products.py
from .db import get_connection

mydb = get_connection()

class Product:

    def __init__(self, name,
                 category_id, price=0.0, 
                 size=0,
                 stock=10, image="", id=None):
        self.name = name
        self.size = size
        self.price = price
        self.stock = stock
        self.category_id = category_id
        self.image = image
        self.id = id

    def save(self):
        if self.id is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO products(name, size, price, stock, category_id, image, id_prom) "
                sql += "VALUES(%s, %s, %s, %s, %s, %s, %s)"
                val = (self.name, self.size, 
                       self.price, self.stock, 
                       self.category_id, self.image, 4)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE products SET name = %s, size = %s, price = %s, "
                sql += "stock = %s, category_id = %s, image = %s WHERE id = %s"
                val = (self.name, self.size, 
                       self.price, self.stock, 
                       self.category_id, self.image, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id

    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM products WHERE id = { id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id

    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM products WHERE id = { id }"
            cursor.execute(sql)
            product = cursor.fetchone()
            if product:
                product = Product(name=product["name"],
                                  size=product["size"],
                                  price=product["price"],
                                  stock=product["stock"],
                                  category_id=product["category_id"],
                                  image=product["image"],
                                  id=product["id"])
                return product
            return None

    @staticmethod
    @staticmethod
    def search(name):
        if name != None:
            with mydb.cursor(dictionary=True) as cursor:
                sql = "SELECT * FROM products LIKE %s WHERE name =  ORDER BY id DESC"
                cursor.execute(sql, (name,))
                product = cursor.fetchone()
                if product:
                    product = Product(name=product["name"],
                                    size=product["size"],
                                    price=product["price"],
                                    stock=product["stock"],
                                    category_id=product["category_id"],
                                    image=product["image"],
                                    id=product["id"])
                    return product
        return None

    
    @staticmethod
    def get_all(limit=10, page=1):
        offset = limit * page - limit
        products = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM products LIMIT { limit } OFFSET { offset }"
            cursor.execute(sql)
            result = cursor.fetchall()
            for product in result:
                products.append(Product(name=product["name"],
                                  size=product["size"],
                                  price=product["price"],
                                  stock=product["stock"],
                                  category_id=product["category_id"],
                                  image=product["image"],
                                  id=product["id"]))
            return products

    @staticmethod
    def get_by_category(id_category):
        products = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM products WHERE category_id = { id_category }"
            cursor.execute(sql)
            result = cursor.fetchall()
            for product in result:
                products.append(Product(name=product["name"],
                                  size=product["size"],
                                  price=product["price"],
                                  stock=product["stock"],
                                  category_id=product["category_id"],
                                  image=product["image"],
                                  id=product["id"]))
            return products
        
    def __str__(self):
        return f"{ self.name } { self.size }"
    
    @staticmethod
    def count():
        with mydb.cursor(dictionary=True) as cursor:
            sql = "SELECT count(id) as total FROM products"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result['total']

app/forms/product_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, FloatField, SelectField
from wtforms.validators import DataRequired, NumberRange
from flask_wtf.file import FileField, FileAllowed

from models.categories import Category

class CreateProductForm(FlaskForm):  
    categories = Category.get_all()
    cats = [(-1, '')]
    for cat in categories:
        cats.append((cat.id, cat.category))
    
    name = StringField('Nombre', 
                           validators=[DataRequired('Este campo es necesario.')])
    price = FloatField('Precio',
                                validators=[DataRequired(), NumberRange(min=0.0, max=None)])
    stock = IntegerField('Existencia',
                                validators=[DataRequired(), NumberRange(min=0.0, max=None)])
    size = IntegerField('Tamaño',
                                validators=[DataRequired()])
    category_id = SelectField('Categoría',
                              choices=cats, coerce=int, validate_choice=False, validators=[DataRequired()])
    image = FileField('Imagen de producto', 
                      validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'Solo imagenes!')])
    submit = SubmitField('Guardar')
    
    
class UpdateProductForm(FlaskForm):
    
    # categories = Category.get_all()
    cats = []
    # for cat in categories:
    #     cats.append((cat.id, cat.category))

    name = StringField('Nombre', 
                       validators=[DataRequired()])
    price = FloatField('Precio', 
                       validators=[DataRequired(), NumberRange(min=0.0, max=None)])
    stock = IntegerField('Existencias', 
                         validators=[DataRequired(), NumberRange(min=0, max=None)])
    size = IntegerField('Tamaño',
                        validators=[DataRequired()])
    category_id = SelectField('Categoría', 
                              choices=cats, coerce=int, validate_choice=False, validators=[DataRequired()])
    image = FileField('Imagen de Ingrediente', 
                      validators=[FileAllowed(['jpg', 'png', 'jpeg', 'jfif'], 'Solo imagenes!')])
    submit = SubmitField('Actualizar')

app/views/product_views.py
from flask import Blueprint, render_template, redirect, url_for, abort, session, request, flash

from models.products import Product 

from forms.product_forms import UpdateProductForm, CreateProductForm

from models.categories import Category

from utils.file_handler import save_image

product_views = Blueprint('product', __name__)

@product_views.route('/products/')
@product_views.route('/products/<int:page>/')
def home(page=1):
    if "user" in session:
        limit = 10
        products = Product.get_all(limit=limit, page=page)
        total_products = Product.count()
        pages = total_products // limit
        user = session.get("user")
        return render_template('products/product.html', products=products, pages=pages, user=user)
    return redirect(url_for('user.login'))

@product_views.route('/products/<int:page>/')
def next(page=2):
    if "user" in session:
        limit = 10
        products = Product.get_all(limit=limit, page=page)
        total_products = Product.count()
        pages = total_products // limit
        user = session.get("user")
        return render_template('products/product.html', products=products, pages=pages, user=user)
    return redirect(url_for('user.login'))

@product_views.route('/products/create/', methods=('GET', 'POST'))
def create():
    if "user" in session:#Linea de sesion
        form = CreateProductForm()
        if form.validate_on_submit():
            name = form.name.data
            price = form.price.data
            stock = form.stock.data
            size = form.size.data
            category_id = form.category_id.data
            f = form.image.data
            image=""
            if f:
                image = save_image(f, 'images/products')
            product = Product(name=name,
                            price=price,
                            stock=stock,
                            size=size,
                            category_id=category_id,
                            image=image)
            print(product)
            product.save()
            return redirect(url_for('product.home'))
        return render_template('products/create_prod.html', form=form)
    return redirect(url_for('user.login'))#LINEA DE SESION 

@product_views.route('/products/<int:id>/update/', methods=('GET', 'POST'))
def update_prod(id):
    if "user" in session:
        form = UpdateProductForm()
        categories = Category.get_all()
        cats = [(-1, '')]
        for cat in categories:
            cats.append((cat.id, cat.category))
        form.category_id.choices = cats
        product = Product.get(id)
        if product is None:
            abort(404)
        if form.validate_on_submit():
            product.name = form.name.data
            product.size = form.size.data
            product.price = form.price.data
            product.stock = form.stock.data
            product.category_id = form.category_id.data
            f = form.image.data
            if f:
                image = save_image(f, 'images/products')
                product.image = image
            product.save()
            return redirect(url_for('product.home'))
        form.name.data = product.name
        form.size.data = product.size
        form.price.data = product.price
        form.stock.data = product.stock
        form.category_id.data = product.category_id
        image = product.image
        return render_template('products/create_prod.html', form=form, image=image)
    return redirect(url_for('user.login'))


@product_views.route('/products/<int:id>/detail/')
def detail(id):
    if "user" in session:
        product = Product.get(id)
        if product is None: abort(404)
        cat = Category.get(product.category_id)
        return render_template('products/details.html', product=product, cat=cat)
    return redirect(url_for('user.login'))

@product_views.route('/product/<int:id>/delete/', methods=['POST'])
def delete(id):
    if "user" in session:
        product = Product.get(id)
        if product is None: abort(404)
        product.delete()
        return redirect(url_for('product.home'))
    return redirect(url_for('user.login'))

@product_views.route('/products/buscar/', methods=['GET','POST'])
def search():
    result = None
    if request.method == "POST":
        result = Product.search(result)
        search  = request.form['buscar']
        return render_template('products/busqueda.html', miData = result, busqueda = search)
    return redirect(url_for('product.home')) 

@product_views.before_request
def antes_de_iniciar():
    ruta = request.path
    if 'user' not in session and ruta != "/products/" and ruta != "/products/create/" and not ruta.startswith("/static"):
        flash("Es necesario iniciar sesion.")
        return redirect(url_for('user.login'))

app/templates/products/busqueda.html
{% extends 'base.html' %}

{% block body %}
<div id="result" class="container">
    <h4>Resultados.. </h4>
    {% if (miData) %} 
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Existencias</th>
            <th>Imagen</th>
            <th>Acciones</th> 
        </tr>
        </thead>
        <tbody>
            {% for product in miData %}
                <tr>
                    <td>{{product.id}}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.stock }}</td>
                    <td>
                        <img src="{{ url_for('static', filename='images/products/' + product.image) }}" alt="" width="100px">
                    </td>
                    <td class="action-cell">
                            <a href="{{ url_for('product.update_prod', id=product.id) }}">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <form action="{{ url_for('product.delete', id=product.id) }}">
                                <button type="submit" onclick="return confirm('Seguro?')">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
        <p>No hay resultados para la busqueda:
            <strong class="busq colorCrimson"> {{ busqueda }}</strong>
        </p>
    {% endif %}
{% endblock %}

app/templates/products/create_prod.html
{% extends 'base.html' %}
{% block title %}
Agregar Producto
{% endblock  %}

{% block content %}
<h1>Agregar Producto</h1>
<form method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div>
        {{ form.name.label }}
        {{ form.name() }}
    </div>
    <div>
        {{ form.price.label }}
        {{ form.price() }}
    </div>
    <div>
        {{ form.stock.label }}    
        {{ form.stock() }}
    </div>
    <div>
        {{ form.size.label }}    
        {{ form.size() }}
    </div>
    <div>
        {{ form.category_id.label }}
        {{ form.category_id() }}
    </div>
    <div>
        {{ form.image.label }}
        {{ form.image() }}
        {% if form.image.errors %}
                {% for error in form.image.errors%}
                <p>{{error}}</p>
                {% endfor %}  
            {% endif %}
    </div>
    {% if image %}
    <div>
        <img src="{{ url_for('static', filename='images/products/' + image) }}" alt="" width="200px">
    </div>
    {% endif %}
    <div>
        {{ form.submit() }}
    </div>
    <a href="{{ url_for('product.home') }}" class="btn btn-warning">Regresar</a>
</form>
{% endblock %}
        

app/templates/products/details.html
{% extends 'base.html' %}

{% block title %}Detalle de Producto{% endblock %}

{% block content %}
<div class="containerDetails">
    <h2>{{ product.name }}</h2>
    <h4>{{ cat.category }}</h4>
    <p>{{ product.description }}</p>
    <img src="{{ url_for('static', filename='images/products/' + product.image) }}" alt=""
    width="300px">
    <p>Precio: ${{ product.price }}</p>
    <a href="javascript:history.back()" class="btn btn-secondary"> Volver Atrás</a>
</div>
{% endblock %}

app/templates/products/product.html
{% extends 'base.html' %}

{% block title %}
Productos
{% endblock %}
    
{% block content %}
<h1>Productos</h1>
<a href="{{ url_for('product.create') }}" class="custom-btn">Nuevo Producto</a>


<table id="products">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Existencias</th>
            <th>Imagen</th>
            <th>Acciones</th> 
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
            <tr>
                <td>
                    <a href="{{ url_for('product.detail', id=product.id) }}">{{ product.id }}</a>
                </td>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.stock }}</td>
                <td class="image-cell">
                    <img src="{{ url_for('static', filename='images/products/' + product.image) }}" alt="" width="100px">
                </td>
                <td class="action-cell">
                    <a href="{{ url_for('product.update_prod', id=product.id) }}" class="action-icon">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <form action="{{ url_for('product.delete', id=product.id) }}" method="post">
                        <button type="submit" onclick="return confirm('Seguro?')" class="action-icon">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                    <a href="{{ url_for('product.detail', id=product.id) }}" class="action-icon">
                        <i class="fa fa-info-circle"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<hr>
{% for i in range(pages) %}
{% endfor %}
{% endblock %}