app/models/promotions.py
from .db import get_connection

mydb = get_connection()

class Promotion:

    def __init__(self, name, description, id=None):
        self.id = id
        self.name = name
        self.description = description

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO promotions(name, description) VALUES(%s, %s)"
                val = (self.name, self.description)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE promotions SET name = %s, description = %s WHERE id = %s"
                val = (self.name, self.description, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM promotions WHERE id = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id
            
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT name, description FROM promotions WHERE id = { id }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            promotion = Promotion(result["name"], result["description"], id)
            return promotion
        
    @staticmethod
    def get_all():
        promotions = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT id, name, description FROM promotions"
            cursor.execute(sql)
            result = cursor.fetchall()
            for item in result:
                promotions.append(Promotion(item["name"], item["description"], item["id"]))
            return promotions
        
    def __str__(self):
        return f"{ self.id } - { self.name }"

app/forms/promotion_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class CreatePromotionForm(FlaskForm):
    name = StringField('Nombre', 
                           validators=[DataRequired()])
    description = TextAreaField('Descripcion',
                                validators=[DataRequired()])
    submit = SubmitField('Guardar')
    
class UpdatePromotionForm(FlaskForm):
    name = StringField('Nombre', 
                           validators=[DataRequired()])
    description = TextAreaField('Descripcion',
                                validators=[DataRequired()])
    submit = SubmitField('Guardar')

app/views/promotion_views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session

from models.promotions import Promotion 

from forms.promotion_forms import UpdatePromotionForm, CreatePromotionForm

promotion_views = Blueprint('promotion', __name__)

@promotion_views.route('/promotions/')
def promotions():
    if "user" in session:
        promotions = Promotion.get_all()
        user = session.get("user")
        return render_template('promotions/promotion.html',
                            promotions=promotions, user=user)
    return redirect(url_for('user.login'))

@promotion_views.route('/promotions/create/', methods=('GET', 'POST'))
def create_prom():
    if "user" in session:
        form = CreatePromotionForm()
        if form.validate_on_submit():
            name = form.name.data
            description = form.description.data
            prom = Promotion(name, description)
            prom.save()
            return redirect(url_for('promotion.promotions'))
        return render_template('promotions/create_prom.html', form=form)
    return redirect(url_for('user.login'))

@promotion_views.route('/promotions/<int:id>/update/', methods=('GET', 'POST'))
def update_prom(id):
    if "user" in session:
        form = UpdatePromotionForm()
        prom = Promotion.get(id)
        if form.validate_on_submit():
            prom.name = form.name.data
            prom.description = form.description.data
            prom.save()
            return redirect(url_for('promotion.promotions'))
        form.name.data = prom.name
        form.description.data = prom.description
        return render_template('promotions/create_prom.html', form=form )
    return redirect(url_for('user.login'))

@promotion_views.route('/promotions/<int:id>/delete/', methods=('GET','POST'))
def delete_prom(id):
    if "user" in session:
        prom = Promotion.get(id)
        prom.delete()
        return redirect(url_for('promotion.promotions'))
    return redirect(url_for('user.login'))

@promotion_views.before_request
def antes_de_iniciar():
    ruta = request.path
    if 'user' not in session and ruta != "/promotions/" and ruta != "/promotions/create/" and not ruta.startswith("/static"):
        flash("Es necesario iniciar sesion.")
        return redirect(url_for('user.login'))

app/templates/promotions/create_prom.html
{% extends 'base.html' %}
{% block title %}
Agregar Promocion 
{% endblock  %}

{% block content %}
<h1>Crear nueva promoción</h1>
<div class="form-container" >
    <form method="post" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div>
            {{form.name.label}}
            {{form.name(placeholder="Nombre")}}
            {% if form.name.errors %}
                {% for error in form.name.errors%}
                <p>{{error}}</p>
                {% endfor %}  
            {% endif %}
        </div>
        <div>
            {{form.description.label}}
            {{form.description(placeholder="Descripción")}}
            {% if form.description.errors %}
                {% for error in form.description.errors%}
                <p>{{error}}</p>
                {% endfor %}  
            {% endif %}
        </div>
        <div>
            {{form.submit(class="btn btn-success")}}
        </div>
    </form>
</div>
<a href="{{ url_for('promotion.promotions') }}" class="btn btn-warning">Regresar</a>
{% endblock %}
        

app/templates/promotions/promotion.html
{% extends 'base.html' %}

{% block title %}
Promociones
{% endblock %}
    
{% block content %}
<h1>Promociones</h1>
<a href="{{ url_for('promotion.create_prom') }}" class="btn btn-success">Nueva Promocion</a>
<table id="promotions">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for prom in promotions %}
            <tr>
                <td>{{ prom.id }}</td>
                <td>{{ prom.name }}</td>
                <td>{{ prom.description }}</td>
                <td>
                    <a href="{{ url_for('promotion.update_prom', id=prom.id) }}">
                        <i class="fa fa-refresh fa-spin"></i>
                    </a>  / 
                    <form method="post" action="{{ url_for('promotion.delete_prom', id=prom.id) }}">
                        <button type="submit"
                            onclick="return confirm('Seguro?')">
                            <i class="fa fa-trash"></i>
                        </button>   
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
    